services:
  postgres:
    image: postgres:16
    container_name: sll-postgres
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
      POSTGRES_DB: lab
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab -d lab"]
      interval: 3s
      timeout: 3s
      retries: 20

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: sll-clickhouse
    environment:
      CLICKHOUSE_USER: lab
      CLICKHOUSE_PASSWORD: lab
      CLICKHOUSE_DB: lab
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch-data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8123/ping || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20

  cassandra:
    image: cassandra:5
    container_name: sll-cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: sll-cluster
      CASSANDRA_DC: dc1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    ports:
      - "9042:9042"
    volumes:
      - cass-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 40
      start_period: 30s

volumes:
  pg-data:
  ch-data:
  cass-data:
